name: plink2
base: core20 # the base snap is the execution environment for this snap
version: '2' # just for humans, typically '1.2+git' or '1.3.2'
summary:  PLINK command-line program for genomics
description:
 Comprehensive update to Shaun Purcell's PLINK command-line program.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
license: GPL-3.0

parts:
    plink2:
        # See 'snapcraft plugins'
        plugin: dump
        source: https://s3.amazonaws.com/plink2-assets/plink2_linux_amd_avx2_20230109.zip
#            organize:
#        "plink2" : bin/
#        source:  ./
        prime:
            - -toy.map
            - -toy.ped

apps:
    plink2:
        command: plink2
        plugs:
          - home
          - network
          - removable-media
          - x11
          - wayland
          - desktop
          - desktop-legacy
          - unity7

#    prettify2:
#        command: prettify2

